// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/time.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRequest) Reset() {
	*x = TimeRequest{}
	mi := &file_proto_time_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRequest) ProtoMessage() {}

func (x *TimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_time_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRequest.ProtoReflect.Descriptor instead.
func (*TimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_time_proto_rawDescGZIP(), []int{0}
}

type TimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixTime      int64                  `protobuf:"varint,1,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeResponse) Reset() {
	*x = TimeResponse{}
	mi := &file_proto_time_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeResponse) ProtoMessage() {}

func (x *TimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_time_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeResponse.ProtoReflect.Descriptor instead.
func (*TimeResponse) Descriptor() ([]byte, []int) {
	return file_proto_time_proto_rawDescGZIP(), []int{1}
}

func (x *TimeResponse) GetUnixTime() int64 {
	if x != nil {
		return x.UnixTime
	}
	return 0
}

var File_proto_time_proto protoreflect.FileDescriptor

const file_proto_time_proto_rawDesc = "" +
	"\n" +
	"\x10proto/time.proto\x12\x05proto\"\r\n" +
	"\vTimeRequest\"+\n" +
	"\fTimeResponse\x12\x1b\n" +
	"\tunix_time\x18\x01 \x01(\x03R\bunixTime2J\n" +
	"\vTimeService\x12;\n" +
	"\x0eGetCurrentTime\x12\x12.proto.TimeRequest\x1a\x13.proto.TimeResponse\"\x00B\tZ\a./protob\x06proto3"

var (
	file_proto_time_proto_rawDescOnce sync.Once
	file_proto_time_proto_rawDescData []byte
)

func file_proto_time_proto_rawDescGZIP() []byte {
	file_proto_time_proto_rawDescOnce.Do(func() {
		file_proto_time_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_time_proto_rawDesc), len(file_proto_time_proto_rawDesc)))
	})
	return file_proto_time_proto_rawDescData
}

var file_proto_time_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_time_proto_goTypes = []any{
	(*TimeRequest)(nil),  // 0: proto.TimeRequest
	(*TimeResponse)(nil), // 1: proto.TimeResponse
}
var file_proto_time_proto_depIdxs = []int32{
	0, // 0: proto.TimeService.GetCurrentTime:input_type -> proto.TimeRequest
	1, // 1: proto.TimeService.GetCurrentTime:output_type -> proto.TimeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_time_proto_init() }
func file_proto_time_proto_init() {
	if File_proto_time_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_time_proto_rawDesc), len(file_proto_time_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_time_proto_goTypes,
		DependencyIndexes: file_proto_time_proto_depIdxs,
		MessageInfos:      file_proto_time_proto_msgTypes,
	}.Build()
	File_proto_time_proto = out.File
	file_proto_time_proto_goTypes = nil
	file_proto_time_proto_depIdxs = nil
}
