version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - GOPROXY=https://goproxy.cn,direct
    ports:
      - "50051:50051"
    networks:
      - grpc-network
    container_name: gRPC-server

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - GOPROXY=https://goproxy.cn,direct
    ports:
      - "8080:8080"
    depends_on:
      - server
    networks:
      - grpc-network
    container_name: gRPC-client

networks:
  grpc-network:
    driver: bridge 